### ISSUE TITLE
Could not get master role for DRM

### ISSUE THREAD

**Issue by spiral009** [embear-engineering/drm-framebuffer#4]
```
.../home/drm-framebuffer # dd if=/dev/urandom | ./drm-framebuffer -d /dev/dri/card0 -c DSI-1
Could not get master role for DRM.
```
and How to use ffmpeg? To get image or videos off of a drm based device such as my phone

**Comment by eichenberger** [comment]
Hi @ulist 

Most likely the error message you see comes because there is something else already using /dev/dri/card0 (e.g. your Desktop environment). Please note this tool is meant for testing graphics integrations and not as a production-ready tool. For doing something like mpeg to drm/kms you should better have a look at something like gstreamer and its [kmssink](https://gstreamer.freedesktop.org/documentation/kms/?gi-language=c#kmssink-page). This tool would be way too slow and inefficient to stream videos.
